name: main workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: devio-api
  AZURE_WEBAPP_PACKAGE_PATH: "./src/DevIO.Api/publish"
  DOTNET_VERSION: "9.x"
  SOLUTION_PATH: "AppWebApiCompleta.sln"
  UNIT_TESTS_PROJECT_PATH: "./tests/DevIO.UnitTests"
  INTEGRATION_TESTS_PROJECT_PATH: "./tests/DevIO.IntegrationTests"
  API_PR0JECT_PATH: "./src/DevIO.Api"
  PUBLISH_DIR: "./publish"

jobs:
  build-app:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout app
        uses: actions/checkout@v4

      - name: Setup .NET version
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
        
      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore

  test-app:
    name: Run automated tests app
    runs-on: ubuntu-latest
    needs: [build-app]
    steps:
      - name: Checkout app
        uses: actions/checkout@v4

      - name: Setup .NET version
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Unit Tests
        run: dotnet test ${{ env.UNIT_TESTS_PROJECT_PATH }} --configuration Release --no-restore --no-build --verbosity normal

      - name: Integration Tests
        run: dotnet test ${{ env.INTEGRATION_TESTS_PROJECT_PATH }} --configuration Release --no-restore --no-build --verbosity normal

  publish-app:
    name: Generate artifacts and dependencies of publishment
    runs-on: ubuntu-latest
    needs: [test-app]
    steps:
      - name: Checkout app
        uses: actions/checkout@v4

      - name: Setup .NET version
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Publish
        run: dotnet publish ${{ env.API_PR0JECT_PATH }} --configuration Release --no-restore --no-build --property:PublishDir=${{ env.PUBLISH_DIR }}

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}