name: Main Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - 'containerzation/**'

env:
  AZURE_WEBAPP_NAME: devio-api
  AZURE_WEBAPP_PACKAGE_PATH: "./src/DevIO.Api/publish"
  DOTNET_VERSION: "9.x"
  SOLUTION_PATH: "AppWebApiCompleta.sln"
  UNIT_TESTS_PROJECT_PATH: "./tests/DevIO.UnitTests"
  INTEGRATION_TESTS_PROJECT_PATH: "./tests/DevIO.IntegrationTests"
  API_PR0JECT_PATH: "./src/DevIO.Api"
  PUBLISH_DIR: "./publish"

jobs:
  build-test-publish:
    name: Build, Test and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Grant access to Github repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
        
      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore
      
      - name: Unit Tests
        run: dotnet test ${{ env.UNIT_TESTS_PROJECT_PATH }} --configuration Release --no-restore --no-build --verbosity normal

      - name: Integration Tests
        run: dotnet test ${{ env.INTEGRATION_TESTS_PROJECT_PATH }} --configuration Release --no-restore --no-build --verbosity normal
      
      - name: Publish
        run: dotnet publish ${{ env.API_PR0JECT_PATH }} --configuration Release --no-restore --no-build --property:PublishDir=${{ env.PUBLISH_DIR }}

      - name: Publish Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: [build-test-publish]
    steps:
      - name: Download artifact from build-test-publish job
        uses: actions/download-artifact@v4
        with:
          name: webapp
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # It's inside repository secrets of github and you need to provide publish profile downloaded inside Azure App Service: https://learn.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel%2Caspnetcore
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}