name: Feature|Hotfix|Refactor Workflows

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/**'
      - 'hotfix/**'
      - 'refactor/**'
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
      - 'containerzation/**'
  # pull_request:
  #   branches:
  #     - 'feature/**'
  #     - 'hotfix/**'
  #     - 'refactor/**'

env:
  DOTNET_VERSION: "9.x"
  SOLUTION_PATH: "AppWebApiCompleta.sln"
  UNIT_TESTS_PROJECT_PATH: "./tests/DevIO.UnitTests"
  INTEGRATION_TESTS_PROJECT_PATH: "./tests/DevIO.IntegrationTests"

#jobs:
  # build-and-test:
  #   name: Build and Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Grant access to Github repository
  #       uses: actions/checkout@v4

  #     - name: Setup .NET
  #       uses: actions/setup-dotnet@v4
  #       with:
  #         dotnet-version: ${{ env.DOTNET_VERSION }}
        
  #     - name: Restore
  #       run: dotnet restore ${{ env.SOLUTION_PATH }}

  #     - name: Build
  #       run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore
      
  #     - name: Unit Tests
  #       run: dotnet test ${{ env.UNIT_TESTS_PROJECT_PATH }} --configuration Release --no-restore --no-build --verbosity normal

  #     - name: Integration Tests
  #       run: dotnet test ${{ env.INTEGRATION_TESTS_PROJECT_PATH }} --configuration Release --no-restore --no-build --verbosity normal

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Executar testes unitários
        run: dotnet test ${{ env.UNIT_TESTS_PROJECT_PATH }} --configuration Release --verbosity normal

  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Baixar artefatos de build
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Executar testes de integração
        run: dotnet test ${{ env.INTEGRATION_TESTS_PROJECT_PATH }} --configuration Release --no-restore --no-build --verbosity normal
